#! /bin/sh

sxhkd &

#monitor setup
#xrandr --output DVI-D-0 --off --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate right --output HDMI-0 --primary --mode 1920x1080 --pos 1080x420 --rotate normal --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --off &

#wallpaper setup
nitrogen --set-zoom-fill /home/paimon/Pictures/background.png &

#polybar 
$HOME/.config/polybar/launch.sh &

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#picom start
picom -b &

bspc monitor -d I II III IV V VI VII


bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
